colors = ["white", "black"]

BaseTemplate = """// File is generated by FieldLookup.py
// In order to change it please modify FieldLookup.py
// run it
// and overlap FieldLookup.hpp by tmp_FieldLookup.hpp

#pragma once

#include <publicIf/Notation.hpp>
static constexpr signed char LINE_8_TO_RIGHT[] = {56, 57, 58, 59, 60, 61, 62, 63, -1, -1, -1, -1, -1, -1, -1, -1};
static constexpr signed char LINE_7_TO_RIGHT[] = {48, 49, 50, 51, 52, 53, 54, 55, -1, -1, -1, -1, -1, -1, -1, -1};
static constexpr signed char LINE_6_TO_RIGHT[] = {40, 41, 42, 43, 44, 45, 46, 47, -1, -1, -1, -1, -1, -1, -1, -1};
static constexpr signed char LINE_5_TO_RIGHT[] = {32, 33, 34, 35, 36, 37, 38, 39, -1, -1, -1, -1, -1, -1, -1, -1};
static constexpr signed char LINE_4_TO_RIGHT[] = {24, 25, 26, 27, 28, 29, 30, 31, -1, -1, -1, -1, -1, -1, -1, -1};
static constexpr signed char LINE_3_TO_RIGHT[] = {16, 17, 18, 19, 20, 21, 22, 23, -1, -1, -1, -1, -1, -1, -1, -1};
static constexpr signed char LINE_2_TO_RIGHT[] = { 8,  9, 10, 11, 12, 13, 14, 15, -1, -1, -1, -1, -1, -1, -1, -1};
static constexpr signed char LINE_1_TO_RIGHT[] = { 0,  1,  2,  3,  4,  5,  6,  7, -1, -1, -1, -1, -1, -1, -1, -1};

static constexpr signed char LINE_8_TO_LEFT[] = {63, 62, 61, 60, 59, 58, 57, 56,, -1, -1, -1, -1, -1, -1, -1, -1};
static constexpr signed char LINE_7_TO_LEFT[] = {55, 54, 53, 52, 51, 50, 49, 48, -1, -1, -1, -1, -1, -1, -1, -1};
static constexpr signed char LINE_6_TO_LEFT[] = {47, 46, 45, 44, 43, 42, 41, 40, -1, -1, -1, -1, -1, -1, -1, -1};
static constexpr signed char LINE_5_TO_LEFT[] = {39, 38, 37, 36, 35, 34, 33, 32, -1, -1, -1, -1, -1, -1, -1, -1};
static constexpr signed char LINE_4_TO_LEFT[] = {31, 30, 29, 28, 27, 26, 25, 24, -1, -1, -1, -1, -1, -1, -1, -1};
static constexpr signed char LINE_3_TO_LEFT[] = {23, 22, 21, 20, 19, 18, 17, 16, -1, -1, -1, -1, -1, -1, -1, -1};
static constexpr signed char LINE_2_TO_LEFT[] = {15,  2,  3,  4,  5,  6,  7,  8, -1, -1, -1, -1, -1, -1, -1, -1};
static constexpr signed char LINE_1_TO_LEFT[] = { 7,  6,  5,  4,  3,  2,  1,  0, -1, -1, -1, -1, -1, -1, -1, -1};

"""
